title: Bruflot
email: git@bruflot.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bruflot.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bruflot
github_username:  bruflot

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1